version: '3.8'

volumes:
  node_data_store:

services:
  nodejs:
    build:
      context: ./infra/nodejs
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    environment:
      - DEBUG=${NODEJS_DEBUG}
      - PORT=${NODEJS_PORT}
    tty: true
    ports:
      - "${NODEJS_DEBUG_PORT}:5050"

  nginx:
    build: 
      context: ./infra/nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"

  postgresql:
    build: 
      context: ./infra/postgresql
    volumes:
      - node_data_store:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
