FROM nginx:1.19.6-alpine

RUN apk update \
    && apk upgrade \
    && apk --update add logrotate \
    && apk add --no-cache openssl \
    && apk add --no-cache bash

RUN apk add --no-cache curl

COPY default.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www

EXPOSE 80