FROM node:12-slim

ENV NODE_ENV="development"

WORKDIR /var/www/

RUN apt-get update && \
  apt-get -y install libpq-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

EXPOSE 3000